@startuml
left to right direction
skinparam packageStyle rectangle
actor customer

rectangle MedTracker {
  customer -- (Create Reminder)
  customer -- (View Reminder)
  customer -- (Update Reminder)
  customer -- (Delete Reminder)
  (Create Reminder) .> (Update Notification/Alarm) : include
  (Update Reminder) .> (Update Notification/Alarm) : include
   (Delete Reminder) .> (Remove Notification/Alarm) : include
note right of (Create Reminder)
UseCaseUC01
end note


note right of (View Reminder)
UseCaseUC02
end note
note right of (Update Reminder)
UseCaseUC03
end note

note right of (Delete Reminder)
UseCaseUC04
end note
}

@enduml